name: 💡 Fiche Idée WIT
description: Proposez une idée ou un besoin à étudier dans le cadre du projet.
labels: [idée, besoin, WIT]
body:
  - type: markdown
    attributes:
      value: |
        Merci de remplir cette fiche pour soumettre une nouvelle idée ou un besoin.

  - type: input
    id: nom
    attributes:
      label: Nom / Prénom
      placeholder: Jean Dupont
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Mail
      placeholder: nom@entreprise.fr

  - type: textarea
    id: besoin
    attributes:
      label: Description du Besoin
      description: Décrivez clairement le besoin ou l’idée à soumettre.
    validations:
      required: true

  - type: checkboxes
    id: marche
    attributes:
      label: Marché cible
      description: Cochez les options qui s'appliquent
      options:
        - label: Exploitants
        - label: Collectivités
        - label: Intégrateurs/Installateurs
        - label: Bureaux d’études
        - label: Client final
        - label: Plateformes (énergétiques ou gestion de données)

  - type: dropdown
    id: cap2030
    attributes:
      label: Adéquation Feuille de route Projet "CAP 2030"
      description: Choisir un axe et expliquez le lien dans le champ suivant.
      options:
        - Axe 1 : Limiter les impacts négatifs liés aux différentes étapes du cycle de vie de nos produits.
        - Axe 2 : Générer un maximum d’impacts positifs à chaque déploiement de nos solutions.
        - Axe 3 : Normaliser de nouveaux indicateurs de performance de nos solutions.
        - Axe 4 : Développer une coopération active avec tous les acteurs de notre écosystème.